library(ggplot2)
iris
which(iris$Sepal.Length)
iris$Sepal.Length
iris$Sepal.Width
mean(iris$Sepal.Length)
mean(iris$Sepal.Width)
mean(iris$Sepal.Length[iris$Petal.Length > 3])
mean(iris$Sepal.Width[iris$Petal.Width > 3])
mean(iris$Sepal.Width[iris$Petal.Length > 3])
library(tidyverse)
?mpg
str(mpg)
View(mpg)
filter(mpg, cty > 27)
filter(mpg, cty > 27, hwy > 30)
filter(mpg, cty > 27, hwy > 40)
filter(mpg, cty > 27 || hwy > 40)
filter(mpg, cty > 27 | hwy > 40)
filter(mpg, manufacturer == "honda")
filter(mpg, manufacturer == "honda", manufacturer == "toyota")
filter(mpg, manufacturer == "honda" | manufacturer == "toyota")
filter(mpg, manufacturer %in% c("honda", "toyota"))
select(mpg, manufacturer)
select(mpg, manufacturer, model)
select(mpg, 1, 3, 4)
select(mpg, 1:4)
select(mpg, -manufacturer)
select(mpg, -manufacturer, -model)
select(mpg, starts_with("m"))
select(mpg, starts_with("d"))
select(filter(mpg, cty > 25), manufacturer, model)
filter(mpg, cty > 25) %>% select(manufacturer, model)
mpg %>% filter(cty > 25) %>% select(manufacturer, model)
select(filter(iris, Petal.Length > 3.0, Petal.Width > 1.0), Sepal.Length, Sepal.Width)
filter(iris, Sepal.Length > 3.0, Sepal.Width > 1.0)
filter(iris, Petal.Length > 3.0, Petal.Width > 1.0) %>% select(Sepal.Length, Sepal.Width)
iris %>% filter(Petal.Length > 3.0, Petal.Width > 1.0) %>% select(Sepal.Length, Sepal.Width)
iris  %>% select(Sepal.Length, Sepal.Width)%>% filter(Petal.Length > 3.0, Petal.Width > 1.0)
select(filter(iris, Petal.Length > 3, Petal.Width > 3))
select(filter(iris, Petal.Length > 3, Petal.Width > 3), starts_with("Sepal"))
select(filter(iris, Petal.Length > 3, Petal.Width > 3), Sepal.Length, Sepal.Width)
select(filter(iris, Petal.Length > 3 & Petal.Width > 3), Sepal.Length, Sepal.Width)
select(filter(iris, Petal.Length > 3 & Petal.Width > 1), Sepal.Length, Sepal.Width)
select(filter(mpg, manufacturer, cty), arrange(desc(cty)))
select(filter(mpg, manufacturer & cty), arrange(desc(cty)))
filter(mpg, manufacturer, cty)
select(filter(iris, Petal.Length > 3 & Petal.Width > 1), Sepal.Length, Sepal.Width)
library(tidyverse)
select(filter(iris, Petal.Length > 3 & Petal.Width > 1), Sepal.Length, Sepal.Width)
mean(iris$Sepal.Length[iris$Petal.Length > 3])
mean(iris$Sepal.Width[iris$Petal.Length > 3])
select(mpg %>% arrange(cty), manufacturer, cty)
library(tidyverse)
View(mpg)
mpg %>% View()
# arrange
mpg %>% arrange(manufacturer)
mpg %>% arrange(cty)
mpg %>% arrange(-cty)
mpg %>% arrange(manufacturer)
mpg %>% arrange(desc(manufacturer))
mpg %>% arrange(cty, hwy)
mpg %>% arrange(desc(cty))
mpg %>% arrange(cty, manufacturer)
mpg %>% select(cty, manufacturer) %>% arrange(cty)
mpg %>% arrange(cty) %>% select(cty, manufacturer)
mpg %>% select(cty, manufacturer, hwy) %>% arrange(cty)
select(mpg %>% arrange(cty), manufacturer, cty)
select(mpg %>% arrange(cty), manufacturer, cty, hwy)
select(mpg %>% arrange(cty, hwy), manufacturer, cty, hwy)
select(mpg %>% arrange(-cty), manufacturer, cty, hwy)
select(mpg %>% arrange(cty), manufacturer, cty, hwy, manufacturer=="audi")
filter(select(mpg %>% arrange(cty), manufacturer, cty, hwy), manufacturer=="audi")
filter(select(mpg %>% arrange(-cty), manufacturer, cty, hwy), manufacturer=="audi")
filter(select(mpg %>% arrange(-cty, cty > 25), manufacturer, cty, hwy), manufacturer=="honda")
mpg
filter(select(mpg %>% arrange(cty, cty > 25), model), manufacturer=="honda")
filter(select(mpg %>% arrange(-cty, cty > 25), model), manufacturer=="honda")
select(filter(select(mpg %>% arrange(-cty, cty > 25), model), manufacturer=="honda"), model)
select(filter(select(mpg %>% arrange(-cty), manufacturer, cty, model), manufacturer=="honda", cty > 25), model)
mpg %>% View()
# mutate
mpg %>% mutate((cty + hwy)/2) %>% View()
mpg %>% mutate(mileage = (cty + hwy)/2) %>% View()
# summarise
mpg %>% summarise(mean(cty))
mpg %>% mean(cty)
mpg %>% summarise(mean(cty), min(cty), max(cty))
mpg %>% summarise(meanCty=mean(cty), minCty = min(cty), maxCty = max(cty))
iris %>% summarise(meanLength=mean(Sepal.Length), meanWidth=mean(Sepal.Width), Sepal.Length > 3.0)
iris %>% filter(Petal.Length > 3) %>% select(Petal.Length, Petal.Width) %>% summarise(mean(Sepal.Length), mean(Septal.Width))
# group_by + summarise
mpg %>% group_by(manufacturer) %>% View()
mpg %>% group_by(manufacturer) %>% summarise(mean(cty)) %>% View()
mpg %>% View()
mpg %>% group_by(manufacturer) %>% summarise(mean(cty)) %>% View()
mpg %>% group_by(year) %>% summarise(mean(cty)) %>% View()
mpg %>% View()
mpg %>% arrange(year) %>% View()
mpg %>% arrange(year) %>% summarise(mean(cty))
mpg %>% group_by(year, manufacturer) %>% summarise(mean(cty)) %>% View()
install.packages("nycflights13")
library(nycflights13)
nycflights13
flights
flights %>% filter(year == 2013, month = 2, day = 12)
library(ggplot2)
library(tidyverse)
library(nycflights13)
flights
flights
View(flights)
flights %>% filter(year == 2013, month == 2, day == 13)
flights %>% filter(dep_delay > 2, arr_delay > 2)
flights %>% filter(dep_delay > 2 | arr_delay > 2)
flights %>% filter(carrier == "UA", carrier == "AA", carrier == "DL")
flights %>% filter(carrier == "UA" | carrier == "AA" | carrier == "DL")
flights %>% arrange(air_time)
flights %>% arrange(-air_time)
flights %>% select(origin, dest, air_time) %>% arrange(air_time)
flights %>% select(origin, dest) %>% arrange(air_time)
flights %>% mutate(total_delay = (dep_de))
flights %>% mutate(total_delay = (dep_delay + arr_delay))
flights %>% mutate(total_delay = (dep_delay + arr_delay)) %>% select(origin, dest, dep_delay, arr_delay, total_delay) %>% arrange(-total_delay)
flights %>% mutate(total_delay = (dep_delay + arr_delay)) %>% select(origin, dest, dep_delay, arr_delay, total_delay) %>% arrange(-total_delay) %>% select(origin, dest)
flights %>% mutate(total_delay = (dep_delay + arr_delay)) %>% select(origin, dest, dep_delay, arr_delay, total_delay) %>% arrange(-total_delay) %>% select(origin, dest) %>% slice(1:10)
flights %>% mutate(total_delay = (dep_delay + arr_delay)) %>% select(origin, dest, dep_delay, arr_delay, total_delay) %>% arrange(-total_delay) %>% select(origin, dest, total_delay) %>% slice(1:10)
flights %>% mutate(total_delay = (dep_delay + arr_delay)) %>% select(dep_delay, arr_delay, origin, total_delay) %>% group_by(origin) %>% summarise(mean(total_delay, na.rm = TRUE))
flights %>% mutate(total_delay = (dep_delay + arr_delay)) %>% select(dep_delay, arr_delay, origin, dest, total_delay) %>% group_by(origin, dest) %>% summarise(mean(total_delay, na.rm = TRUE))
mpg
mpg %>% slice(1)
mpg %>% slice(5)
mpg %>% slice(1:5)
mpg %>% slice(seq(1,5))
mpg %>% slice(seq(1,5, by=2))
mpg %>% max(cty)
mpg %>% summarise(max(cty))
mpg %>% arrange(cty)
mpg %>% arrange(-cty) %>% slice(1)
mpg %>% arrange(-cty) %>% slice(1:3)
mpg %>% top_n(n=3, wt=cty)
View(mpg)
mpg$mileage
mpg %>% select(mean(cty), mean(hwy))
mpg %>% select(mean(mpg$cty), mean(hwy))
mpg %>% select(cty, hwy) %>% arrange(year)
mpg %>% select(displ, cyl, cty, hwy)
mpg %>% select(manufacturer, cty) %>% group_by(manufacturer)
mpg %>% select(manufacturer, cty, hwy) %>% group_by(manufacturer)
mpg %>% select(manufacturer, cty, hwy) %>% group_by(manufacturer) %>% summarise(mean(cty))
mpg %>% select(manufacturer, cty, hwy) %>% group_by(manufacturer) %>% summarise(mean(cty)) %>% summarise(mean(hwy))
mpg %>% select(manufacturer, cty, hwy) %>% group_by(manufacturer) %>% summarise(mean(hwy))
mpg %>% select(manufacturer, cty) %>% group_by(manufacturer) %>% summarise(mean(cty)) %>% slice(1:3)
mpg %>% group_by(manufacturer) %>% summarise(mean(cty)) %>% arrange(-'mean(cty)') %>% slice(1:3)
mpg %>% group_by(manufacturer) %>% summarise(mean(cty)) %>% arrange(-`mean(cty)`) %>% slice(1:3)
mpg %>% group_by(manufacturer) %>% summarise(mean(cty)) %>% top_n(n=3, wt=mean(cty))
mpg %>% group_by(manufacturer) %>% summarise(mean(cty)) %>% top_n(n=3, mean(cty))
mpg
mpg %>% group_by(manufacturer) %>% summarise(mean_cty=mean(cty)) %>% top_n(n=3, wt=mean_cty)
mpg %>% group_by(manufacturer) %>% summarise(mean_city=mean(cty)) %>% arrange(-mean_city) %>% top_n(n=3, wt=mean_city)
mpg %>% group_by(manufacturer) %>% summarise(mean_city=mean(cty)) %>% arrange(-mean_city) %>% top_n(n=4, wt=mean_city)
band_members
band_instruments
band_members %>% inner_join(band_instruments)
band_members %>% left_join(band_instruments)
band_members %>% right_join(band_instruments)
band_members
band_members_4rows <- band_members %>% add_row(name="Paul", band="Wings")
band_members
band_members_4rows
band_instruments_4rows <- band_instruments %>% add_row(name="Paul", plays="vocals")
band_instruments_4rows
band_members_4rows %>% inner_join(band_instruments_4rows)
band_members_4rows
band_members_4rows %>% left_join(band_instruments_4rows)
band_instruments_4rows %>% full_join(band_instruments_4rows)
band_instruments_4rows
band_members_4rows %>% full_join(band_instruments_4rows)
band_members_4rows %>% right_join(band_instruments_4rows)
band_members
band_instruments2
band_members %>% inner_join(band_instruments2)
band_members %>% inner_join(band_instruments2, by=name)
band_members %>% inner_join(band_instruments2, by=c(name="artist"))
band_members_4rows
band_instruments_4rows
band_members_4rows %>% semi_join
band_members_4rows %>% semi_join(band_instruments_4rows)
band_members_4rows
band_instruments_4rows
band_members_4rows %>% anti_join(band_instruments_4rows)
band_instruments_4rows %>% anti_join(band_members_4rows)
library(nycflights13)
flights %>% mutate(flights, (total_delay = dep_delay + arr_delay))
flights %>% mutate(total_delay = (arr_delay + dep_delay)) %>% select(origin, dest, total_delay) %>% arrange(desc(total_delay)) %>% slice(1:10)
library(tidyverse)
enrollment <- tibble(Year = c(2024, rep(2023, each=3), rep(2022, each=2), rep(2021,each=3), rep(seq(2020,2019,by=-1), each=2), 2018), Semester = c("Spring", "Fall", "Summer", "Spring", "Summer", "Spring", "Fall", "Summer", rep(c("Spring","Fall"), times=3)), Enrolled = c(74,26,34,85,21,79,42,34,79,44,57,36,70,45))
enrollment
survey <- read_csv("surveydataSpring2024.csv")
survey
survey_responses <- survey %>% group_by(Year, Semester) %>% tally() %>% rename(Responses = n)
survey_responses
enrollment %>% inner_join(survey_responses) %>% select(Year, Semester, Responses, Enrolled)
library(tidyverse)
relig_income
relig_income %>% pivot_longer(cols=-religion, names_to="income", values_to="freq")
View(relig_income)
relig_income %>% pivot_longer(cols=2:11, names_to="income", values_to="freq")
relig_income %>% pivot_longer(cols=c(`<$10k`,`$10-20k`,`$20-30k`,`$30-40k`,`$40-50k`,`$50-75k`, `$75-100k`, `$100-150k`), names_to="income", values_to="freq")
table4a
table4a %>% pivot_longer(cols=-country, names_to="Years", values_to="Frequency")
grades <- tibble(CWID=c(1234567, 2356902, 5005667), NAME=c("Mary", "Lee", "Elena"), CPSC120=c(3, 4, NA), CPSC121=c(3.3, 3, 2), CPSC131=c(3, 4, 3.7), MATH338=c(3, NA, 3.3))
grades
grades %>% pivot_longer(c("CPSC120", "CPSC121", "CPSC131", "MATH338"), names_to = "Course", values_to = "Grade")
tidyverse
library(tidyverse)
table2
table2 %>% pivot_wider(values_from = count, names_from = type)
library(tidyverse)
language_diversity <- read_csv("language_diversity.csv")
language_diversity
language_diversity %>% pivot_wider(values_from = Value, names_from = Measurement)
language_diversity %>% pivot_wider(values_from = Value, names_from = Measurement) %>% group_by(Continent) %>% summarise(sum(Langs))
language_diversity %>% pivot_wider(values_from = Value, names_from = Measurement) %>% mutate(PopulationDensity = (Population/Area)) %>% group_by(Country) %>% summarise(PopulationDensity)
table3
table3 %>% separate(col = rate, into=c("cases", "population"))
billboard
