iris
library(tidyverse)
View(iris)
ggplot(data = iris) + geom_point(mapping = aes(x = Petal.Width, y = Petal.Length))
ggplot(data = iris) + geom_point(mapping = aes(x = Petal.Width, y = Petal.Length, color = Species))
kmeans(iris[,3:4], centers = 3)
km <- kmeans(iris[,3:4], centers = 3)
ggplot(data = iris) + geom_point(mapping = aes(x = Petal.Width, y = Petal.Length, color = Species)) + geom_point(data = km$centers, mapping = aes(x = Petal.Width, y = Petal.Length, color = Species))
class(km$centers)
class(as.data.frame(km$centers))
class(km$centers)
ggplot(data = iris) + geom_point(mapping = aes(x = Petal.Width, y = Petal.Length, color = Species)) + geom_point(data = as.data.frame(km$centers), mapping = aes(x = Petal.Width, y = Petal.Length), color = "red")
ggplot(data = iris) + geom_point(mapping = aes(x = Petal.Width, y = Petal.Length, color = Species)) + geom_point(data = as.data.frame(km$centers), mapping = aes(x = Petal.Width, y = Petal.Length), color = "red", size = 5)
km$cluster
table(iris$Species, km$cluster)
km <- kmeans(iris[,3:4], centers = 3)
table(iris$Species, km$cluster)
km <- kmeans(iris[,3:4], centers = 3)
table(iris$Species, km$cluster)
km <- kmeans(iris[,3:4], centers = 3, nstart = 2)
table(iris$Species, km$cluster)
irismean <- kmeans(iris[, 1:4], centers = 3)
table(iris$Species, irismean$cluster)
irismean <- kmeans(iris[, 1:4], centers = 3, nstart = 2)
table(iris$Species, irismean$cluster)
ggplot(data = iris) + geom_point(mapping = aes(x = Petal.Width, y = Petal.Length, color = Species)) + geom_point(data = as.data.frame(km$centers), mapping = aes(x = Petal.Width, y = Petal.Length), color = "red", size = 5)
irismean <- kmeans(iris[, 1:4], centers = 3, nstart = 2)
table(iris$Species, irismean$cluster)
ggplot(data = iris) + geom_point(mapping = aes(x = Petal.Width, y = Petal.Length, color = Species)) + geom_point(data = as.data.frame(km$centers), mapping = aes(x = Petal.Width, y = Petal.Length), color = "red", size = 5)
