?nottem
class(nottem)
plot(nottem)
as.vector(nottem)
nottem.vec <- as.vector(nottem)
acf(nottem.vec)
nottem.ts <- ts(nottem.vec)
nottem.ts <- ts(nottem.vec, frequency = 12)
plot(decompose(nottem.ts))
nottem.ts <- ts(nottem.vec, frequency = 7)
plot(decompose(nottem.ts))
acf(nottem.vec, lag.max = 100)
# classwork
library(tidyverse)
temperature <- read_csv("https://raw.githubusercontent.com/jbrownlee/Datasets/master/daily-min-temperatures.csv")
temperature
# 4 graphs
temperature.vec <- as.vector(temperature)
acf(temperature.vec)
acf(temperature, lag.max = 100)
temperature.ts <- ts(temperature, frequency = 500)
plot(decompose(temperature.ts))
temperature.ts <- ts(temperature, frequency = 50)
plot(decompose(temperature.ts))
# choosing one graph (temperature only)
temperature.vec <- as.vector(temperature$Temp)
acf(temperature.vec, lag.max = 500)
temperature.ts <- ts(temperature.vec, frequency = 365)
plot(decompose(temperature.ts))
