library(ggplot2)
esoph
str(esoph)
summary(esoph)
class(esoph$tobgp)
typeof(esoph$tobgp)
help(esoph)
ggplot(data=esoph) + geom_histogram(mapping = aes(x=ncases)) + labs(x="Cases of Esophageal Cancer")
sort(esoph$ncases)
ggplot(data=esoph) + geom_bar(mapping=aes(x=ncases, fill=agegp)) + labs(x="Cases of Esophageal Cancer", y=NULL, fill="Age Group")
ggplot(data=esoph) + geom_bar(mapping=aes(x=agegp, fill=alcgp)) + labs(x="Age Group", y="Count", fill="Alcohol Consumption")
ggplot(data=esoph) + geom_boxplot(mapping=aes(y=ncontrols, x=alcgp)) + labs(x="Alcohol Consumption", y="Number of Controls", title= "Relationship between Number of Controls and Alcohol Consumption")
ggplot(data=esoph) + geom_point(mapping=aes(x=ncases, y=ncontrols)) + labs(x="Number of Cases", y="Number of Controls")
ggplot(data=esoph) + geom_point(mapping=aes(x=ncases, y=ncontrols, color=alcgp)) + labs(x="Number of Cases", y="Number of Controls", color="Alcohol Consumption")
