# Group Members: Angela DeLeo, Roman Saddi, Kinsey Vo
library(tidyverse)
bodyfat <- read_csv("bodyfat.csv")
ggplot(data = bodyfat) + geom_point(mapping = aes(x = Height, y = BodyFat))
bodyfat
bodyfat <- bodyfat %>% filter(Height > 60)
ggplot(data = bodyfat) + geom_point(mapping = aes(x = Height, y = BodyFat))
round(mean(bodyfat$Height), digits = 5)
round(mean(bodyfat$Height))
mod <- lm(data = bodyfat, formula = BodyFat~Height)
summary(mod)
mod <- lm(data = bodyfat, formula = BodyFat~Weight)
summary(mod)
ggplot(data = bodyfat) +geom_point(mapping = aes(x = Height, y = BodyFat)) + geom_abline(intercept = coef(mod)[1], slope = coef(mod)[2], color = "blue")
bodyfat <- bodyfat %>% mutate(resid=residuals(mod))
ggplot(data = bodyfat) + geom_histogram(mapping = aes(resid))
predx <- data.frame(Weight=c(150, 300))
predict(mod, predx, interval = "confidence", level = 0.99)
mod <- lm(data = bodyfat, formula = BodyFat ~ Weight + Height)
summary(mod)
predx <- data.frame(Weight=c(150, 300), Height=70)
predict(mod, predx, interval = "confidence", level = 0.99)
library(modelr)
bodyfat <- bodyfat %>% mutate(BMI = (Weight/(Height^2)))
bodyfat.BMI.model <- lm(data = bodyfat, formula = BodyFat~BMI)
summary(bodyfat.BMI.model)
ggplot(data = bodyfat) + geom_point(mapping = aes(x = BMI, y = BodyFat)) + geom_abline(intercept = coef(bodyfat.BMI.model)[1], slope = coef(bodyfat.BMI.model)[2], color = "red")
predx <- data.frame(Weight=c(150, 300), Height=70)
predx$BMI <- (predx$Weight / (predx$Height^2))
predict(bodyfat.BMI.model, predx, interval = "confidence", level = 0.99)
bodyfat <- bodyfat %>% mutate(AgeGroup = cut(Age, breaks = c(-Inf, 40, 60, Inf), labels = c("Young", "Middle", "Senior")))
bodyfat.AgeGroup.model <- lm(data = bodyfat, formula = BodyFat ~ BMI + AgeGroup)
summary(bodyfat.AgeGroup.model)
bodyfat <- bodyfat %>% add_predictions(bodyfat.AgeGroup.model)
ggplot(data = bodyfat) + geom_point(mapping = aes(x = BMI, y = BodyFat)) + geom_line(mapping = aes(x = BMI, y = pred, color = AgeGroup), linewidth = 1)
bodyfat
bodyfat %>% View()
